
FROM postgres:11

# build postres container with jwt included
RUN apt-get update && apt-get install -y make git postgresql-server-dev-11 postgresql-11-pgtap

# set up jwt tokens
RUN mkdir "/postgres-jwt"
WORKDIR "/postgres-jwt"
COPY . .
RUN make && make install

# fire up postres with new config file
CMD ["postgres"]

